PSDscAllowDomainUser: true
Environment: Prod
Description: This is a ESXI Host description
Role: Prod_EsxHosts
PSDscAllowPlainTextPassword: true
EsxHost:
  Server: vcenter-prod.domain
  Name: Prod_ESXiHost2
NodeName: Prod_ESXiHost2

